In [7]:
import ast
import numpy as np
import pandas as pd
import warnings
from collections import Counter
from winedge import Card, Evaluator

In [8]:
pk = pd.read_csv('dataframe/poker_dataframe.csv')

pk_rvr2 = pk[(~pk['River'].isnull()) & (~pk['SB cards'].isnull()) & (~pk['BB cards'].isnull())]

In [9]:
warnings.filterwarnings('ignore')
pk_rvr2['Board'] = np.nan
pk_rvr2['Flush Count'] = np.nan
pk_rvr2['Flush'] = np.nan

In [10]:
pk_rvr2 = pk_rvr2.reset_index()
pk_rvr2

,index,Game ID,File,Player SB,Player BB,Preflop actions,Flop actions,Turn actions,River actions,Flop,Turn,River,SB stack,BB stack,SB cards,BB cards,Folded pre,Board,Flush Count,Flush
0,1,603604223,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,ArcticWin,Ceaban,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('b', '0.04'), ('c', '0.04')]","['5c', '9c', '5s']",7h,2c,2.00,1.00,"[ Qh, Tc ]","[ 6h, 2h ]",False,NaN,NaN,NaN
1,9,603607691,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,grandiozzo,MARUSYA94,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['9d', '4d', '9s']",Kh,6h,1.20,0.80,"[ 5c, 4c ]","[ 3h, 7s ]",False,NaN,NaN,NaN
2,14,603607964,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,grandiozzo,gunchozaurs,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['Qs', '8s', '5s']",4s,4c,2.63,2.01,"[ Kh, 9c ]","[ 2c, Jh ]",False,NaN,NaN,NaN
3,15,603607982,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,gunchozaurs,grandiozzo,"[('r', '0.03'), ('c', '0.02')]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('b', '0.02'), ('c', '0.02')]","['6s', '7s', '5h']",7c,2d,2.65,2.00,"[ 5c, Ad ]","[ 6h, 9h ]",False,NaN,NaN,NaN
4,27,502906150,Bayamo-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,JillybeanG,Dbloy,"[('r', '0.03'), ('r', '0.10'), ('r', '0.16'), ...",NaN,NaN,NaN,"['7d', '4h', '7s']",Qc,6c,1.81,0.52,"[ Jh, Kh ]","[ Qh, Qd ]",False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86059,520795,553224321,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,silviu2010,Sensei.Dbb,"[('c', '0.01'), ('k', 0)]","[('b', '0.02'), ('c', '0.02')]","[('b', '0.02'), ('c', '0.02')]","[('b', '0.06'), ('c', '0.06')]","['6c', 'Jc', '3d']",2h,9c,0.96,0.89,"[ 5d, Jh ]","[ Ad, As ]",False,NaN,NaN,NaN
86060,520796,553224342,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,Sensei.Dbb,roghnov,"[('c', '0.01'), ('r', '0.02'), ('c', '0.02')]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['7s', 'Jd', '5h']",8c,Js,1.00,1.00,"[ 9s, Qd ]","[ 6c, Ac ]",False,NaN,NaN,NaN
86061,520797,553224357,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,roghnov,Sensei.Dbb,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('b', '0.02'), ('c', '0.02')]","[('k', 0), ('b', '0.02'), ('c', '0.02')]","[('k', 0), ('k', 0)]","['Jd', 'As', 'Qd']",Js,Ts,1.04,0.96,"[ 9s, Ad ]","[ Qh, 7s ]",False,NaN,NaN,NaN
86062,520798,553224367,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,Sensei.Dbb,roghnov,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['4d', '2d', 'Js']",Jd,Ts,1.10,0.90,"[ Qc, Kc ]","[ 9s, Ks ]",False,NaN,NaN,NaN
86063,520803,553224834,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,John_Efapi,mikvell,"[('r', '0.05'), ('c', '0.04')]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['9d', 'Qc', '5d']",7d,Ac,3.42,1.84,"[ 3d, 3s ]","[ 4h, Ah ]",False,NaN,NaN,NaN

In [11]:
for loc in pk_rvr2.index:
    board_str = ast.literal_eval(pk_rvr2['Flop'][loc]) + [pk_rvr2['Turn'][loc], pk_rvr2['River'][loc]]
    pk_rvr2['Board'][loc] = board_str

In [12]:
for games in pk_rvr2.index:
    suits=[]
    for i in range(5):
        suits.append(pk_rvr['Board'][games][i][1])
    counts = Counter(suits)
    count = max(counts.values())
    if count == 1:
        Flush = 0
    elif count ==2:
        Flush = 0
    elif count == 3:
        Flush = 1
    elif count == 4:
        Flush = 2
    else:
        Flush = 3
    pk_rvr2['Flush Count'][games] = count
    pk_rvr2['Flush'][games] = Flush

In [14]:
pk_rvr

,index,Game ID,File,Player SB,Player BB,Preflop actions,Flop actions,Turn actions,River actions,Flop,Turn,River,SB stack,BB stack,SB cards,BB cards,Folded pre,Board,Flush Count,Flush
0,1,603604223,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,ArcticWin,Ceaban,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('b', '0.04'), ('c', '0.04')]","['5c', '9c', '5s']",7h,2c,2.00,1.00,"[ Qh, Tc ]","[ 6h, 2h ]",False,"[5c, 9c, 5s, 7h, 2c]",3.0,1.0
1,9,603607691,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,grandiozzo,MARUSYA94,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['9d', '4d', '9s']",Kh,6h,1.20,0.80,"[ 5c, 4c ]","[ 3h, 7s ]",False,"[9d, 4d, 9s, Kh, 6h]",2.0,0.0
2,14,603607964,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,grandiozzo,gunchozaurs,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['Qs', '8s', '5s']",4s,4c,2.63,2.01,"[ Kh, 9c ]","[ 2c, Jh ]",False,"[Qs, 8s, 5s, 4s, 4c]",4.0,2.0
3,15,603607982,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,gunchozaurs,grandiozzo,"[('r', '0.03'), ('c', '0.02')]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('b', '0.02'), ('c', '0.02')]","['6s', '7s', '5h']",7c,2d,2.65,2.00,"[ 5c, Ad ]","[ 6h, 9h ]",False,"[6s, 7s, 5h, 7c, 2d]",2.0,0.0
4,27,502906150,Bayamo-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,JillybeanG,Dbloy,"[('r', '0.03'), ('r', '0.10'), ('r', '0.16'), ...",NaN,NaN,NaN,"['7d', '4h', '7s']",Qc,6c,1.81,0.52,"[ Jh, Kh ]","[ Qh, Qd ]",False,"[7d, 4h, 7s, Qc, 6c]",2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86059,520795,553224321,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,silviu2010,Sensei.Dbb,"[('c', '0.01'), ('k', 0)]","[('b', '0.02'), ('c', '0.02')]","[('b', '0.02'), ('c', '0.02')]","[('b', '0.06'), ('c', '0.06')]","['6c', 'Jc', '3d']",2h,9c,0.96,0.89,"[ 5d, Jh ]","[ Ad, As ]",False,"[6c, Jc, 3d, 2h, 9c]",3.0,1.0
86060,520796,553224342,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,Sensei.Dbb,roghnov,"[('c', '0.01'), ('r', '0.02'), ('c', '0.02')]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['7s', 'Jd', '5h']",8c,Js,1.00,1.00,"[ 9s, Qd ]","[ 6c, Ac ]",False,"[7s, Jd, 5h, 8c, Js]",2.0,0.0
86061,520797,553224357,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,roghnov,Sensei.Dbb,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('b', '0.02'), ('c', '0.02')]","[('k', 0), ('b', '0.02'), ('c', '0.02')]","[('k', 0), ('k', 0)]","['Jd', 'As', 'Qd']",Js,Ts,1.04,0.96,"[ 9s, Ad ]","[ Qh, 7s ]",False,"[Jd, As, Qd, Js, Ts]",3.0,1.0
86062,520798,553224367,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,Sensei.Dbb,roghnov,"[('c', '0.01'), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['4d', '2d', 'Js']",Jd,Ts,1.10,0.90,"[ Qc, Kc ]","[ 9s, Ks ]",False,"[4d, 2d, Js, Jd, Ts]",3.0,1.0
86063,520803,553224834,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,John_Efapi,mikvell,"[('r', '0.05'), ('c', '0.04')]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","[('k', 0), ('k', 0)]","['9d', 'Qc', '5d']",7d,Ac,3.42,1.84,"[ 3d, 3s ]","[ 4h, Ah ]",False,"[9d, Qc, 5d, 7d, Ac]",3.0,1.0