In [2]:
import pandas as pd

In [3]:
df = pd.read_pickle("../dataframe/poker_dataframe.pkl")
df

,Game ID,File,Player SB,Player BB,Preflop actions,Flop actions,Turn actions,River actions,Flop,Turn,River,SB stack,BB stack,SB cards,BB cards,Folded pre
0,502874582,Arezzo-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,Oracool1,sirstadiljus,"[(f, 0)]",None,None,None,None,None,None,1.22,2.01,None,None,True
1,603604223,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,ArcticWin,Ceaban,"[(c, 0.01), (k, 0)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[(b, 0.04), (c, 0.04)]","[5c, 9c, 5s]",7h,2c,2,1,"[ Qh, Tc ]","[ 6h, 2h ]",False
2,603604231,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,Ceaban,ArcticWin,"[(f, 0)]",None,None,None,None,None,None,1.94,1.06,None,None,True
3,603604236,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,ArcticWin,Ceaban,"[(f, 0)]",None,None,None,None,None,None,1.95,1.05,None,None,True
4,603604241,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,Ceaban,ArcticWin,"[(f, 0)]",None,None,None,None,None,None,1.94,1.06,None,None,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520806,553224385,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,Sensei.Dbb,roghnov,"[(c, 0.01), (k, 0)]","[(k, 0), (b, 0.02), (f, 0)]",None,None,"[Kc, 5d, 5s]",None,None,1.02,0.98,None,None,False
520807,553224389,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,roghnov,Sensei.Dbb,"[(r, 0.03), (f, 0)]",None,None,None,None,None,None,1,1,None,None,False
520808,553224821,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,mikvell,John_Efapi,"[(c, 0.01), (k, 0)]","[(b, 0.04), (c, 0.04)]","[(k, 0), (b, 0.08), (f, 0)]",None,"[9h, 6h, 7h]",Ks,None,3.36,1.90,None,None,False
520809,553224834,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,John_Efapi,mikvell,"[(r, 0.05), (c, 0.04)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[9d, Qc, 5d]",7d,Ac,3.42,1.84,"[ 3d, 3s ]","[ 4h, Ah ]",False
520810,553224845,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,mikvell,John_Efapi,"[(c, 0.01), (k, 0)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[(b, 0.06), (f, 0)]","[8s, Td, Tc]",4c,Jh,3.48,1.78,None,None,False

In [ ]:
example= df['Flop actions'][1]

In [ ]:
example

[('k', 0), ('k', 0)]

In [ ]:
type(example)

list

In [ ]:
type(example[0])

tuple

In [11]:
def check_aggression(action_list):
    """
    This function looks at the actions that happened and outputs a 2 digit number
    The number represents aggression show by either player

    Player counts as aggressive if they raised or bet

    Ex:
    00 - means both passive
    10 means SB aggressive BB passive
    01 means SB passive BB aggressive
    11 means both aggressive
    """
    agg_sb=0
    agg_bb =0

    if action_list==None:
        return None
    for index,action in enumerate(action_list):
        if action[0] in ('r','b'):
            if index %2==0:
                agg_sb=1
            else:
                agg_bb=1
    return agg_sb, agg_bb

In [12]:
check_aggression(example)

(0, 0)

In [45]:
df['preflop aggression']=check_aggression(df['Preflop actions'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [44]:
df['Aggr preflop'] = df['Preflop actions'].apply(check_aggression)
df['Aggr flop'] = df['Flop actions'].apply(check_aggression)
df['Aggr turn'] = df['Turn actions'].apply(check_aggression)
df['Aggr river'] = df['River actions'].apply(check_aggression)

In [16]:
df

,Game ID,File,Player SB,Player BB,Preflop actions,Flop actions,Turn actions,River actions,Flop,Turn,River,SB stack,BB stack,SB cards,BB cards,Folded pre,Aggr preflop,Aggr flop,Aggr turn,Aggr river
0,502874582,Arezzo-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,Oracool1,sirstadiljus,"[(f, 0)]",None,None,None,None,None,None,1.22,2.01,None,None,True,"(0, 0)",None,None,None
1,603604223,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,ArcticWin,Ceaban,"[(c, 0.01), (k, 0)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[(b, 0.04), (c, 0.04)]","[5c, 9c, 5s]",7h,2c,2,1,"[ Qh, Tc ]","[ 6h, 2h ]",False,"(0, 0)","(0, 0)","(0, 0)","(1, 0)"
2,603604231,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,Ceaban,ArcticWin,"[(f, 0)]",None,None,None,None,None,None,1.94,1.06,None,None,True,"(0, 0)",None,None,None
3,603604236,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,ArcticWin,Ceaban,"[(f, 0)]",None,None,None,None,None,None,1.95,1.05,None,None,True,"(0, 0)",None,None,None
4,603604241,Asmara-0.01-0.02-USD-NoLimitHoldem-Pacific-6-4...,Ceaban,ArcticWin,"[(f, 0)]",None,None,None,None,None,None,1.94,1.06,None,None,True,"(0, 0)",None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520806,553224385,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,Sensei.Dbb,roghnov,"[(c, 0.01), (k, 0)]","[(k, 0), (b, 0.02), (f, 0)]",None,None,"[Kc, 5d, 5s]",None,None,1.02,0.98,None,None,False,"(0, 0)","(0, 1)",None,None
520807,553224389,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,roghnov,Sensei.Dbb,"[(r, 0.03), (f, 0)]",None,None,None,None,None,None,1,1,None,None,False,"(1, 0)",None,None,None
520808,553224821,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,mikvell,John_Efapi,"[(c, 0.01), (k, 0)]","[(b, 0.04), (c, 0.04)]","[(k, 0), (b, 0.08), (f, 0)]",None,"[9h, 6h, 7h]",Ks,None,3.36,1.90,None,None,False,"(0, 0)","(1, 0)","(0, 1)",None
520809,553224834,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,John_Efapi,mikvell,"[(r, 0.05), (c, 0.04)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[9d, Qc, 5d]",7d,Ac,3.42,1.84,"[ 3d, 3s ]","[ 4h, Ah ]",False,"(1, 0)","(0, 0)","(0, 0)","(0, 0)"
520810,553224845,Corrientes-0.01-0.02-USD-NoLimitHoldem-Pacific...,mikvell,John_Efapi,"[(c, 0.01), (k, 0)]","[(k, 0), (k, 0)]","[(k, 0), (k, 0)]","[(b, 0.06), (f, 0)]","[8s, Td, Tc]",4c,Jh,3.48,1.78,None,None,False,"(0, 0)","(0, 0)","(0, 0)","(1, 0)"

In [17]:
type(df['Flop'])

pandas.core.series.Series

[('c', '0.01'), ('k', 0)]